allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': true
  '@tailwindcss/oxide': false
  esbuild: false
  maplibre-gl: false
  prisma: true
  sharp: false
  unrs-resolver: false
  vue-demi: false
